Repository near-daos/sputnik-dao-contract, pull requests merged in 2022-03, with the labels that each got.

#131 Refactor OldAccountId logic merged in PR #130
  Cargo.lock
  sputnik-staking/res/sputnik_staking.wasm
  sputnikdao-factory2/res/sputnikdao_factory2.wasm
  sputnikdao2/res/sputnikdao2.wasm
  sputnikdao2/src/bounties.rs
  sputnikdao2/src/lib.rs
  sputnikdao2/src/proposals.rs
  sputnikdao2/src/types.rs
  sputnikdao2/tests/utils/mod.rs
  test-token/res/test_token.wasm
Labels: P-High, C-housekeeping, S-L2

#134 DAO self upgrade via proposals
  Cargo.lock
  sputnik-staking/res/sputnik_staking.wasm
  sputnikdao-factory2/res/sputnikdao_factory2.wasm
  sputnikdao-factory2/src/lib.rs
  sputnikdao2/res/sputnikdao2.wasm
  sputnikdao2/tests-ava/README.md
  sputnikdao2/tests-ava/__tests__/lib.ava.ts
  sputnikdao2/tests-ava/__tests__/upgrade.ava.ts
  sputnikdao2/tests-ava/__tests__/utils.ts
  test-token/res/test_token.wasm
Labels: P-Critical, C-bug, C-discussion, S-L3

#112 Tests list
  README.md
  sputnik-staking/README.md
  sputnikdao-factory2/README.md
  sputnikdao-factory2/res/sputnikdao_factory2.wasm
  sputnikdao2/ABI.md
  sputnikdao2/TestPlan.md
  sputnikdao2/tests-ava/__tests__/bounties.ava.ts
  sputnikdao2/tests-ava/__tests__/proposals.ava.ts
Labels: P-High, C-docs, S-L2, C-Testing

#111 Adding scripts to help the upgrade process
  scripts/deploy_factory_dev.sh
  scripts/upgrade_dao_direct_dev.sh
  scripts/upgrade_dao_proposal_dev.sh
  sputnikdao-factory2/res/sputnikdao_factory2.wasm
Labels: P-High, C-Enhancement, C-housekeeping, C-docs, S-L2
